import "./global.css";
import { UiLayout } from "../components/ui/ui-layout";
import { ClusterProvider } from "../components/cluster/cluster-data-access";
import { SolanaProvider } from "../components/solana/solana-provider";
import { ReactQueryProvider } from "./react-query-provider";
import { Orbitron } from "next/font/google";

export const metadata = {
	title: "action-chaining",
	description: "Generated by create-solana-dapp",
};

const links: { label: string; path: string }[] = [
	{ label: "Account", path: "/account" },
	{ label: "Clusters", path: "/clusters" },
];

const orbitron = Orbitron({ subsets: ["latin"] });

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={orbitron.className}>
				<ReactQueryProvider>
					<ClusterProvider>
						<SolanaProvider>
							<UiLayout links={links}>{children}</UiLayout>
						</SolanaProvider>
					</ClusterProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
