import './global.css'
import GlobalProvider from 'global-provider/global-provider'
import { Orbitron } from 'next/font/google'
import { UiLayout } from '../components/ui/ui-layout'

export const metadata = {
    title: 'action-chaining',
    description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
    { label: 'Account', path: '/account' },
    { label: 'Clusters', path: '/clusters' },
]

const orbitron = Orbitron({ subsets: ['latin'] })

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={orbitron.className}>
                <GlobalProvider>
                    <UiLayout links={links}>{children}</UiLayout>
                </GlobalProvider>
            </body>
        </html>
    )
}
